CREATE VIEW ORDER_PROCESS_DB.ORDER_XFRM.V_SALES_ORDER_DETAIL AS
SELECT ORDER_ID,ORDER_DATE,CUSTOMER_ID,ITEM_ID,QTY,TOTAL_AMOUNT,CREATE_DATE,CREATE_USER,CREATE_USER,PRICE   FROM ORDER_PROCESS_DB.ORDER_BASE.T_SALES_ORDER_DETAIL;
